import "../styles/services.css";
export default function Services() {
  return (
    <div className="container-slider">
      <div className="slider">
        <div className="slider-track">
          <div className="slide">
            <nav>
              <ul>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
                <li>OLá Mundo</li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  );
}
